sudo: required
dist: xenial
os: linux
language: minimal
cache:
  directories:
  - depends/built
  - depends/sdk-sources
  - $HOME/.ccache

env:
  global:
    - MAKEJOBS=-j3
    - RUN_TESTS=false
    - RUN_FORMATTING_CHECK=false
    - CHECK_DOC=0
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - USE_CLANG=false
    - SDK_URL=https://www.bitcoinunlimited.info/sdks
    - PYTHON_DEBUG=1
    - WINEDEBUG=fixme-all
    - PPA=ppa:bitcoin-unlimited/bu-ppa

matrix:
  include:
    #bitcoind clang
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-5.0
          packages:
            - clang-5.0
      env:
        - USE_CLANG=true
        - CXX=clang++-5.0 CC=clang-5.0
        - CXXFLAGS="-std=c++11"
        - HOST=x86_64-unknown-linux-gnu
        - RUN_TESTS=false
        - PACKAGES="python3-zmq libzmq3-dev clang-format-3.8 build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev"
        - GOAL="install" BITCOIN_CONFIG="--enable-zmq CC=clang-5.0 CXX=clang++-5.0 CPPFLAGS=-DDEBUG_LOCKORDER"
    #bitcoind
    - compiler: gcc
      env:
        - CXX=g++ CC=gcc
        - HOST=x86_64-unknown-linux-gnu PACKAGES="python3-zmq clang-format-3.8" DEP_OPTS="NO_UPNP=1 DEBUG=1" RUN_TESTS=true RUN_FORMATTING_CHECK=true GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER"
    #ARM64
    - compiler: gcc
      env:
        - CXX=g++ CC=gcc
        - HOST=aarch64-linux-gnu PACKAGES="g++-aarch64-linux-gnu" GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
    #ARM32
    - compiler: gcc
      env:
        - CXX=g++ CC=gcc
        - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
    #Win32
    - compiler: gcc
      env:
        - CXX=g++ CC=gcc
        - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
    #Linux32-bit + dash
    - compiler: gcc
      env:
        - CXX=g++ CC=gcc
        - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash"
    #Win64
    - compiler: gcc
      env:
        - CXX=g++ CC=gcc
        - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" DEP_OPTS="" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-reduce-exports"
    - compiler: gcc
      env:
        - CXX=g++ CC=gcc
        - HOST=x86_64-unknown-linux-gnu PACKAGES="python3 python3-zmq libzmq3-dev qtbase5-dev qttools5-dev-tools protobuf-compiler libdbus-1-dev libharfbuzz-dev" DEP_OPTS="ALLOW_HOST_PACKAGES=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
    #Cross-Mac
    - compiler: gcc
      env:
        - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev clang-3.8 libc++-dev" BITCOIN_CONFIG="--enable-reduce-exports" OSX_SDK=10.11 GOAL="deploy"

before_install:
    - set -o errexit; source .travis/before_install.sh

install:
    - set -o errexit; source .travis/install.sh

before_script:
    - set -o errexit; source .travis/before_script.sh

script:
    - if [ $SECONDS -gt 1200 ]; then set +o errexit; echo "Travis early exit to cache current state"; false; else set -o errexit; source .travis/script.sh; fi

after_script:
    - set -o errexit; cd $TRAVIS_BUILD_DIR; source .travis/after_script.sh

after_failure:
    - set -o errexit; cd $TRAVIS_BUILD_DIR; source .travis/after_failure.sh
